name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Получаем код из репозитория
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Важно для SonarCloud анализа

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          pip install uv
          make install

      # 4. Запускаем линтер и тесты
      - name: Run linter and pytest
        run: |
          make check

      # 5. Генерируем отчет о покрытии
      - name: Run test coverage
        run: |
          make test-coverage

      # 6. Запускаем анализ в SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=VitalRusinov_python-project-50
            -Dsonar.organization=vitalrusinov
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**